package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type ReportHandler struct {
}

func NewReportHandler() *ReportHandler {
	return &ReportHandler{}
}

// GetReport handles GET /api/v1/report/:symbol
func (h *ReportHandler) GetReport(c *gin.Context) {
	symbol := c.Param("symbol")
	c.JSON(http.StatusOK, gin.H{
		"symbol":         symbol,
		"data_available": false,
		"message":        "Reports are not available yet under the normalized schema.",
	})
}

// GenerateReport handles POST /api/v1/report/:symbol/generate
// This endpoint triggers report generation (async via Python worker)
func (h *ReportHandler) GenerateReport(c *gin.Context) {
	symbol := c.Param("symbol")

	// Note: In a production system, this would trigger the Python worker
	// via a queue (Redis) or direct API call. For now, we return instructions.

	c.JSON(http.StatusOK, gin.H{
		"message": "Report generation triggered",
		"symbol":  symbol,
		"note":    "Report will be generated by Python worker. Use GET /api/v1/report/:symbol to retrieve it after generation.",
		"status":  "queued",
	})
}

// ListReports handles GET /api/v1/reports
func (h *ReportHandler) ListReports(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"reports": []map[string]interface{}{},
		"count":   0,
	})
}
