-- No-op under normalized v2 schema.
-- `stock_news` is defined in 001 and is keyed by `stock_id`.
-- Earnings, peers, refresh tracking, and live prices will be reintroduced later
-- with `stock_id` foreign keys and consistent provider-agnostic contracts.
