-- Add missing tables that the application expects

-- Table for storing fundamentals snapshots
CREATE TABLE IF NOT EXISTS fundamentals_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    stock_symbol TEXT NOT NULL,
    as_of_date DATE NOT NULL,
    source TEXT,
    payload JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Indexes for fundamentals_snapshots
CREATE INDEX IF NOT EXISTS idx_fundamentals_snapshots_symbol_date 
ON fundamentals_snapshots(stock_symbol, as_of_date DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fundamentals_snapshots_symbol_asof
ON fundamentals_snapshots(stock_symbol, as_of_date);

-- Table for auditing data fetch operations
CREATE TABLE IF NOT EXISTS data_fetch_audit (
    audit_id TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    fetch_type TEXT NOT NULL,
    fetch_mode TEXT,
    fetch_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_source TEXT,
    rows_fetched INTEGER NOT NULL DEFAULT 0,
    rows_saved INTEGER NOT NULL DEFAULT 0,
    fetch_duration_ms INTEGER,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    error_message TEXT,
    validation_report_id TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for data_fetch_audit
CREATE INDEX IF NOT EXISTS idx_data_fetch_audit_symbol_timestamp 
ON data_fetch_audit(symbol, fetch_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_data_fetch_audit_type_timestamp 
ON data_fetch_audit(fetch_type, fetch_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_data_fetch_audit_success_timestamp
ON data_fetch_audit(success, fetch_timestamp DESC);

-- Table for raw market data (daily)
CREATE TABLE IF NOT EXISTS raw_market_data_daily (
    stock_symbol TEXT NOT NULL,
    trade_date DATE NOT NULL,
    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    adj_close DOUBLE PRECISION,
    volume BIGINT,
    source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (stock_symbol, trade_date)
);

-- Indexes for raw_market_data_daily
CREATE INDEX IF NOT EXISTS idx_raw_market_data_daily_symbol_date 
ON raw_market_data_daily(stock_symbol, trade_date DESC);

-- Table for daily indicators
CREATE TABLE IF NOT EXISTS indicators_daily (
    stock_symbol TEXT NOT NULL,
    trade_date DATE NOT NULL,
    sma_50 DOUBLE PRECISION,
    sma_200 DOUBLE PRECISION,
    ema_20 DOUBLE PRECISION,
    rsi_14 DOUBLE PRECISION,
    macd DOUBLE PRECISION,
    macd_signal DOUBLE PRECISION,
    macd_hist DOUBLE PRECISION,
    signal TEXT,
    confidence_score DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (stock_symbol, trade_date)
);

-- Indexes for indicators_daily
CREATE INDEX IF NOT EXISTS idx_indicators_daily_symbol_date 
ON indicators_daily(stock_symbol, trade_date DESC);

-- Table for industry peers
CREATE TABLE IF NOT EXISTS industry_peers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_symbol TEXT NOT NULL,
    sector TEXT,
    industry TEXT,
    peer_symbol TEXT NOT NULL,
    peer_name TEXT,
    market_cap BIGINT,
    similarity_score DOUBLE PRECISION,
    data_source TEXT,
    last_updated TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (stock_symbol, peer_symbol)
);

-- Indexes for industry_peers
CREATE INDEX IF NOT EXISTS idx_industry_peers_symbol 
ON industry_peers(stock_symbol);

CREATE INDEX IF NOT EXISTS idx_industry_peers_industry 
ON industry_peers(industry);

-- Table for data ingestion state
CREATE TABLE IF NOT EXISTS data_ingestion_state (
    stock_symbol TEXT NOT NULL,
    dataset TEXT NOT NULL,
    interval TEXT NOT NULL,
    source TEXT,
    historical_start_date DATE,
    historical_end_date DATE,
    cursor_date DATE,
    cursor_ts TIMESTAMPTZ,
    last_attempt_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'idle',
    error_message TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (stock_symbol, dataset, interval)
);

-- Indexes for data_ingestion_state
CREATE INDEX IF NOT EXISTS idx_data_ingestion_state_symbol_type 
ON data_ingestion_state(stock_symbol, dataset);

CREATE INDEX IF NOT EXISTS idx_data_ingestion_state_status 
ON data_ingestion_state(status);
